select 
SALESORDERID
, REVISIONNUMBER
, ORDERDATE
, DUEDATE
, SHIPDATE
, STATUS
, ONLINEORDERFLAG
, SALESORDERNUMBER
, PURCHASEORDERNUMBER
, ACCOUNTNUMBER
, CUSTOMERID
, SALESPERSONID
, TERRITORYID
, BILLTOADDRESSID
, SHIPTOADDRESSID
, SHIPMETHODID
, CREDITCARDID
, CREDITCARDAPPROVALCODE
, CURRENCYRATEID
, SUBTOTAL
, TAXAMT
, FREIGHT
, TOTALDUE
, COMMENT
, ROWGUID
, MODIFIEDDATE
from {{ source('dbt_adventure_works', 'seed_sales_order_header') }} 
where 1 = 1 
